#!/bin/bash
set -e -E -u

VERSION=$(lsb_release -is 2> /dev/null || uname)
echo "setting up development environment for $VERSION"
VENV=venv
echo "virtualenv dir is $VENV"

case $VERSION in
    ManjaroLinux)
        virtualenv --version > /dev/null 2>&1 || sudo pacman -S python-virtualenv
        ;;
    Ubuntu)
        virtualenv --version > /dev/null 2>&1 || sudo apt-get install virtualenv
        ;;
    Darwin)
        virtualenv --version > /dev/null 2>&1 || brew install pyenv-virtualenv
        ;;
    Linux)
        virtualenv --version > /dev/null 2>&1 || sudo yum install python-virtualenv
	;;
    *)
        echo "unkonwn system $VERSION"
        exit 1
        ;;
esac

rm -rf $VENV
virtualenv $VENV
set +u
source $VENV/bin/activate
set -u

pip install pybuilder
pyb install_dependencies

(cd $VENV/bin; ln -sf ../../src/main/scripts/* .)
(cd $VENV/lib/python*/site-packages; ln -sf ../../../../src/main/python/* .)

pyb -X

echo "done."
